rules:
  default:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - continuous-integration/travis-ci
          - continuous-integration/appveyor
          - codecov
          - pyup.io/safety-ci
