pull_request_rules:
- name: Default merge for PRs
  actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
    delete_head_branch: {}
  conditions:
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - status-success=build (ubuntu-latest, 3.8)
  - status-success=build (windows-latest, 3.8)
  - status-success=build (macos-latest, 3.8)
  - status-success=codecov/project
  - status-success=pyup.io/safety-ci

- name: Automatic Merge for my PRs
  actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
    delete_head_branch: {}
  conditions:
  - label!=no-mergify
  - author=NeonGraal
  - status-success=build (ubuntu-latest, 3.8)
  - status-success=build (windows-latest, 3.8)
  - status-success=build (macos-latest, 3.8)
  - status-success=codecov/project
  - status-success=pyup.io/safety-ci

- name: Automatic merge for PyUp PRs
  conditions:
  - label!=no-mergify
  - author=pyup-bot
  - status-success=build (ubuntu-latest, 3.8)
  - status-success=build (windows-latest, 3.8)
  - status-success=build (macos-latest, 3.8)
  - status-success=codecov/project
  - status-success=pyup.io/safety-ci
  actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
    delete_head_branch: {}
