pull_request_rules:
- name: Default merge for PRs
  actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
    delete_head_branch: {}
  conditions:
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - status-success=Travis CI - Pull Request
  - status-success=continuous-integration/appveyor/pr
  - status-success=codecov/project
  - status-success=pyup.io/safety-ci
- name: Automatic Merge for my PRs
  actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
    delete_head_branch: {}
  conditions:
  - label!=no-mergify
  - author=neongraal
  - status-success=Travis CI - Pull Request
  - status-success=continuous-integration/appveyor/pr
  - status-success=codecov/project
  - status-success=pyup.io/safety-ci
  
- name: Automatic merge for PyUp PRs
  conditions:
  - label!=no-mergify
  - author=pyup-bot
  - status-success=Travis CI - Pull Request
  - status-success=continuous-integration/appveyor/pr
  - status-success=codecov/project
  - status-success=pyup.io/safety-ci
  actions:
    merge:
      method: merge
      rebase_fallback: merge
      strict: true
    delete_head_branch: {}
